python3 question.py question1 topType awardPrice distance
python3 question.py question1 typeOfContract awardPrice distance

python3 question.py question2 department_suppliers awardPrice numberTenders
python3 question.py question2 department_buyers awardPrice numberTenders

python3 question.py question2_W department_suppliers awardPrice numberTenders
python3 question.py question2_W department_buyers awardPrice numberTenders

python3 question.py question2_U department_suppliers awardPrice numberTenders
python3 question.py question2_U department_buyers awardPrice numberTenders

python3 question.py question2_S department_suppliers awardPrice numberTenders
python3 question.py question2_S department_buyers awardPrice numberTenders